# Let us start with a simple equation y = x*x*y + x + b

### First steps with TensorFlow

In [1]:
import tensorflow as tf

### Define  variables

In [2]:
x = tf.Variable(3, name='x')
y = tf.Variable(4, name='y')

In [6]:
f=x*x*y + y + 2

In [7]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)

In [8]:
result=sess.run(f)

In [9]:
print(result)

42


### Same code with placeholders

In [10]:
x = tf.placeholder(dtype=tf.float32,shape=(None), name='x')
y = tf.placeholder(dtype=tf.float32,shape=(None), name='x')
w = tf.Variable(1.0, name='weight')
w2 = tf.Variable(1.0, name='weight2')
b = tf.Variable(2.0, name='bias')

In [12]:
z = w*x*x*y + w2*x+ b

In [13]:
#initialize the variables
init = tf.global_variables_initializer()

#provide values to placeholders during session runtime
with tf.Session() as sess:
   
    sess.run(init)  
    for t in [1.0, 0.6]:
        for u in [2.0, -1.4]:
            print('x=%4.1f , y=%4.1f --> z=%4.1f'%(
                  t, u, sess.run(z, feed_dict={x:t,y:u})))   

x= 1.0 , y= 2.0 --> z= 5.0
x= 1.0 , y=-1.4 --> z= 1.6
x= 0.6 , y= 2.0 --> z= 3.3
x= 0.6 , y=-1.4 --> z= 2.1


### Working with array structures

In [14]:
#CellStrat - In the code below, we will create a rank-3 tensor of size batchsize x 2 x 3.
#We will reshape it, and calculate column sums.
#Note that -1 in the reshape command indicates that particular dimension will be calculated
#dynamically.
#Therefore, tf.reshape(tensor, shape=(-1,)) can be used to flatten a tensor.

In [16]:
x = tf.placeholder(dtype=tf.float32, shape=(None, 2, 3),  name='input_x')
x
x2 = tf.reshape(x, shape=(-1, 6),name='x2')
xsum = tf.reduce_sum(x2, axis=0, name='col_sum')

## calculate the mean of each column
xmean = tf.reduce_mean(x2, axis=0, name='col_mean')

In [19]:
import numpy as np
with tf.Session() as sess:    
    x_array = np.arange(36).reshape(-1, 2, 3)
    print('input shape: ', x_array.shape)
    
    #x2 has shape =(-1, 6), hence to accomodate 36 elements, it will become shape (6, 6)
    print('Reshaped:\n', 
          sess.run(x2, feed_dict={x:x_array}))
    print(x2)
    print('Column Sums:\n', 
          sess.run(xsum, feed_dict={x:x_array}))
    print('Column Means:\n', 
          sess.run(xmean, feed_dict={x:x_array}))


input shape:  (6, 2, 3)
Reshaped:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
Tensor("x2_1:0", shape=(?, 6), dtype=float32)
Column Sums:
 [ 90.  96. 102. 108. 114. 120.]
Column Means:
 [15. 16. 17. 18. 19. 20.]
