### CellStrat Hub Pack - Deep Learning

#### DL1 - Basic Exercise

# Let us start with a simple equation y = x*x*y + x + b

### First steps with TensorFlow

In [1]:
pip install tensorflow

     |██████████████████████████▏     | 371.4 MB 84.4 MB/s eta 0:00:01

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



     |████████████████████████████████| 454.3 MB 9.2 kB/s  eta 0:00:01
     |████████████████████████████████| 4.0 MB 60.6 MB/s eta 0:00:01
     |████████████████████████████████| 6.0 MB 46.5 MB/s eta 0:00:01
     |████████████████████████████████| 42 kB 1.8 MB/s  eta 0:00:01
     |████████████████████████████████| 129 kB 81.0 MB/s eta 0:00:01
     |████████████████████████████████| 462 kB 79.5 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 45.6 MB/s eta 0:00:01
     |████████████████████████████████| 65 kB 5.5 MB/s  eta 0:00:01
     |████████████████████████████████| 97 kB 9.6 MB/s  eta 0:00:01
     |████████████████████████████████| 146 kB 75.9 MB/s eta 0:00:01
     |████████████████████████████████| 781 kB 63.6 MB/s eta 0:00:01
     |████████████████████████████████| 4.9 MB 50.7 MB/s eta 0:00:01
     |████████████████████████████████| 155 kB 68.8 MB/s eta 0:00:01
     |████████████████████████████████| 147 kB 67.8 MB/s eta 0:00:01
  Created wheel for termcolor: file

In [2]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

### Define  variables

In [3]:
x = tf.Variable(3, name='x')
y = tf.Variable(4, name='y')

In [4]:
f=x*x*y + y + 2

In [5]:
sess = tf.compat.v1.Session()
sess.run(x.initializer)
sess.run(y.initializer)

In [6]:
result=sess.run(f)

In [7]:
print(result)

42


### Same code with placeholders

In [8]:
x = tf.compat.v1.placeholder(dtype=tf.float32,shape=(None), name='x')
y = tf.compat.v1.placeholder(dtype=tf.float32,shape=(None), name='y')
w = tf.Variable(1.0, name='weight')
w2 = tf.Variable(1.0, name='weight2')
b = tf.Variable(2.0, name='bias')

In [9]:
z = w*x*x*y + w2*x+ b

In [10]:
#initialize the variables
init = tf.compat.v1.global_variables_initializer()

#provide values to placeholders during session runtime
with tf.compat.v1.Session() as sess:

    sess.run(init)
    for t in [1.0, 0.6]:
        for u in [2.0, -1.4]:
            print('x=%4.1f , y=%4.1f --> z=%4.1f'%(
                  t, u, sess.run(z, feed_dict={x:t,y:u})))

x= 1.0 , y= 2.0 --> z= 5.0
x= 1.0 , y=-1.4 --> z= 1.6
x= 0.6 , y= 2.0 --> z= 3.3
x= 0.6 , y=-1.4 --> z= 2.1


### Working with array structures

In [11]:
#CellStrat - In the code below, we will create a rank-3 tensor of size batchsize x 2 x 3.
#We will reshape it, and calculate column sums.
#Note that -1 in the reshape command indicates that particular dimension will be calculated
#dynamically.
#Therefore, tf.reshape(tensor, shape=(-1,)) can be used to flatten a tensor.

In [12]:
x = tf.compat.v1.placeholder(dtype=tf.float32, shape=(None, 2, 3),  name='input_x')
x
x2 = tf.reshape(x, shape=(-1, 6),name='x2')
xsum = tf.reduce_sum(input_tensor=x2, axis=0, name='col_sum')

## calculate the mean of each column
xmean = tf.reduce_mean(input_tensor=x2, axis=0, name='col_mean')

In [13]:
import numpy as np
with tf.compat.v1.Session() as sess:
    #np.arange produces digits upto the value listed.
    #Check https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
    x_array = np.arange(36).reshape(-1, 2, 3)

    print('input shape: ', x_array.shape)
    print(x_array)

    #x2 has shape =(-1, 6), hence to accomodate 36 elements, it will become shape (6, 6)
    print('Reshaped:\n',
          sess.run(x2, feed_dict={x:x_array}))
    print('Column Sums:\n',
          sess.run(xsum, feed_dict={x:x_array}))
    print('Column Means:\n',
          sess.run(xmean, feed_dict={x:x_array}))


input shape:  (6, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]]
Reshaped:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
Column Sums:
 [ 90.  96. 102. 108. 114. 120.]
Column Means:
 [15. 16. 17. 18. 19. 20.]
