### CellStrat Hub Pack - Deep Learning

#### DL3 - Perceptron (Iris)

In [1]:
#Import required libraries 
import keras #library for neural network
import pandas as pd #loading data in table form  
import seaborn as sns #visualisation 
import matplotlib.pyplot as plt #visualisation
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import normalize #machine learning algorithm library

In [2]:
#Reading data 
data=pd.read_csv("./iris.csv")
print("Describing the data: ",data.describe())
print("Info of the data:",data.info())

Describing the data:         sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
mem

In [3]:
print(data["variety"].unique())

['Setosa' 'Versicolor' 'Virginica']


In [4]:
# Convert the species into each respective category to be feed into the neural network
data.loc[data["variety"]=="Setosa","variety"]=0
data.loc[data["variety"]=="Versicolor","variety"]=1
data.loc[data["variety"]=="Virginica","variety"]=2
print(data.head())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0


In [5]:
data=data.iloc[np.random.permutation(len(data))]
print(data.head())

     sepal.length  sepal.width  petal.length  petal.width variety
122           7.7          2.8           6.7          2.0       2
23            5.1          3.3           1.7          0.5       0
21            5.1          3.7           1.5          0.4       0
132           6.4          2.8           5.6          2.2       2
135           7.7          3.0           6.1          2.3       2


In [6]:
# Converting data to numpy array in order for processing
X=data.iloc[:,1:4].values
y=data.iloc[:,4].values

print("Shape of X",X.shape)
print("Shape of y",y.shape)
print("Examples of X\n",X[:3])
print("Examples of y\n",y[:3])

Shape of X (150, 3)
Shape of y (150,)
Examples of X
 [[2.8 6.7 2. ]
 [3.3 1.7 0.5]
 [3.7 1.5 0.4]]
Examples of y
 [2 0 0]


In [7]:
#Normalization
X_normalized=normalize(X,axis=0)
print("Examples of X_normalised\n",X_normalized[:3])

Examples of X_normalised
 [[0.07403367 0.1318369  0.11502424]
 [0.08725397 0.03345115 0.02875606]
 [0.09783021 0.02951572 0.02300485]]


In [8]:
#Creating train,test and validation data
'''
80% -- train data
20% -- test data
'''
total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

print("Length of train set x:",X_train.shape[0],"y:",y_train.shape[0])
print("Length of test set x:",X_test.shape[0],"y:",y_test.shape[0])

Length of train set x: 120 y: 120
Length of test set x: 30 y: 30


In [9]:
#Neural network module
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from keras.layers.normalization import BatchNormalization 
from keras.utils import np_utils

In [10]:
#Change the label to one hot vector
'''
[0]--->[1 0 0]
[1]--->[0 1 0]
[2]--->[0 0 1]
'''
y_train=np_utils.to_categorical(y_train,num_classes=3)
y_test=np_utils.to_categorical(y_test,num_classes=3)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)

Shape of y_train (120, 3)
Shape of y_test (30, 3)


In [11]:
import tensorflow as tf

In [12]:
model = tf.keras.models.Sequential()
model.add(keras.layers.Dense(3, kernel_initializer='zeros', name='dense_layer', activation='relu'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [13]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=1000,epochs=30,verbose=1)

Epoch 1/30
1/1 [==============================] - 1s 735ms/step - loss: nan - accuracy: 0.3417 - val_loss: nan - val_accuracy: 0.3000
Epoch 2/30
1/1 [==============================] - 0s 22ms/step - loss: nan - accuracy: 0.3417 - val_loss: nan - val_accuracy: 0.3000
Epoch 3/30
1/1 [==============================] - 0s 22ms/step - loss: nan - accuracy: 0.3417 - val_loss: nan - val_accuracy: 0.3000
Epoch 4/30
1/1 [==============================] - 0s 23ms/step - loss: nan - accuracy: 0.3417 - val_loss: nan - val_accuracy: 0.3000
Epoch 5/30
1/1 [==============================] - 0s 23ms/step - loss: nan - accuracy: 0.3417 - val_loss: nan - val_accuracy: 0.3000
Epoch 6/30
1/1 [==============================] - 0s 22ms/step - loss: nan - accuracy: 0.3417 - val_loss: nan - val_accuracy: 0.3000
Epoch 7/30
1/1 [==============================] - 0s 22ms/step - loss: nan - accuracy: 0.3417 - val_loss: nan - val_accuracy: 0.3000
Epoch 8/30
1/1 [==============================] - 0s 22ms/step - los

In [14]:
prediction=model.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )

Accuracy of the dataset 30.0


In [15]:
#Single Layer Perceptron 
model1=Sequential()
model1.add(Dense(1000,input_dim=3,activation='relu'))
model1.add(Dropout(0.2))
model1.add(Dense(3,activation='softmax'))
model1.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1000)              4000      
_________________________________________________________________
dropout (Dropout)            (None, 1000)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 3003      
Total params: 7,003
Trainable params: 7,003
Non-trainable params: 0
_________________________________________________________________


In [16]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=1000,epochs=30,verbose=1)

Epoch 1/30
1/1 [==============================] - 20s 20s/step - loss: 1.0991 - accuracy: 0.3250 - val_loss: 1.0946 - val_accuracy: 0.3000
Epoch 2/30
1/1 [==============================] - 0s 25ms/step - loss: 1.0947 - accuracy: 0.2917 - val_loss: 1.0916 - val_accuracy: 0.6000
Epoch 3/30
1/1 [==============================] - 0s 25ms/step - loss: 1.0903 - accuracy: 0.5750 - val_loss: 1.0893 - val_accuracy: 0.6000
Epoch 4/30
1/1 [==============================] - 0s 25ms/step - loss: 1.0868 - accuracy: 0.6583 - val_loss: 1.0875 - val_accuracy: 0.6000
Epoch 5/30
1/1 [==============================] - 0s 26ms/step - loss: 1.0842 - accuracy: 0.6583 - val_loss: 1.0860 - val_accuracy: 0.6000
Epoch 6/30
1/1 [==============================] - 0s 25ms/step - loss: 1.0825 - accuracy: 0.6750 - val_loss: 1.0845 - val_accuracy: 0.6000
Epoch 7/30
1/1 [==============================] - 0s 24ms/step - loss: 1.0801 - accuracy: 0.6833 - val_loss: 1.0832 - val_accuracy: 0.6000
Epoch 8/30
1/1 [===========

In [17]:
prediction=model1.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )

Accuracy of the dataset 60.0
